---
- name: Install HTTPD and VSFTPD on all hosts
  hosts: all
  become: true
  import_playbook: testyaml.yaml

  tasks:
    - name: uninstall the package vsftpd
      ansible.builtin.package:
        name: vsftpd
        state: absent

