---
- name: Import the first test configuration
  ansible.builtin.import_playbook: testyaml.yaml

- name: Install HTTPD and VSFTPD on all hosts
  hosts: all
  become: true

  tasks:
    - name: uninstall the package vsftpd
      ansible.builtin.package:
        name: vsftpd
        state: absent

